version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=management_order'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    networks:
      - management-network

  redis:
    image: 'redis/redis-stack:latest'
    labels:
      - "org.springframework.boot.service-connection=redis"
    ports:
      - '6379:6379'
    networks:
      - management-network

networks:
  management-network:
    driver: bridge
